# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================
am:
  podName: "{{ .Values.global.baseNameAM }}-{{ .Values.global.clusterId }}"
  serviceName: "{{ .Values.global.serviceNameAM }}"
  secretName: "{{ .Values.global.baseNameAM }}-{{ .Values.global.clusterId }}"
  image: "{{ .Values.global.registryURL }}/forgerock-access-manager:{{ .Values.global.imageTag }}"
  replicas: 1
  # Below for setting up Hostalias to make AM server FQDN resolvable
  amSiteFqdn: "amdc1.midships.io"
  uri: "am"
  portHttp: 8080
  portHttps: 8443
aps:
  podName: "{{ .Values.global.baseNameAPS }}-{{ .Values.global.clusterId }}"
  secretName: "{{ .Values.global.baseNameAPS }}-{{ .Values.global.clusterId }}"
  configmapName: "{{ .Values.global.baseNameAPS }}-{{ .Values.global.clusterId }}"
tokenstore:
  podName: "{{ .Values.global.baseNameTS }}-{{ .Values.global.clusterId }}"
  secretName: "{{ .Values.global.baseNameTS }}-{{ .Values.global.clusterId }}"
userstore:
  podName: "{{ .Values.global.baseNameUS }}-{{ .Values.global.clusterId }}"
  secretName: "{{ .Values.global.baseNameUS }}-{{ .Values.global.clusterId }}"
fact:
  podName: "{{ .Values.global.baseNameFACT }}-{{ .Values.global.clusterId }}"
  image: "{{ .Values.global.registryURL }}/midships-fact:{{ .Values.global.imageTag }}"
  configmapName: "{{ .Values.global.baseNameFACT }}-{{ .Values.global.clusterId }}"
  config_dir: "/opt/am/config"
  port: "8082"