# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================
userstore:
  configmapName: "{{ tpl .Values.userstore.podName . }}"
  hostAliases_hostname1: "{{ tpl .Values.userstore.podNameDc2 . }}-0.{{ tpl .Values.userstore.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_hostname2: "{{ tpl .Values.userstore.podNameDc2 . }}-1.{{ tpl .Values.userstore.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_hostname3: "{{ tpl .Values.userstore.podNameDc2 . }}-2.{{ tpl .Values.userstore.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_ip1: ""
  hostAliases_ip2: ""
  hostAliases_ip3: ""
  image: "{{ .Values.global.registryURL }}/forgerock-user-store:{{ .Values.global.imageTag }}"
  podName: "{{ .Values.global.baseNameUS }}-{{ .Values.global.clusterId }}"
  podNameDc2: "{{ .Values.global.baseNameUS }}-{{ .Values.global.clusterId2 }}"
  port_replication: "8989"
  portAdmin: "4444"
  portHttp: "8080"
  portHttps: "8443"
  portLdap: "1389"
  portLdaps: "1636"
  pvcSize: "20Gi"
  replicas: 2
  secretName: "{{ tpl .Values.userstore.podName . }}"
  serviceName: "{{ .Values.global.serviceNameUS }}"
replserver:
  configmapName: "{{ tpl .Values.replserver.podName . }}"
  hostAliases_hostname1: "{{ tpl .Values.replserver.podNameDc2 . }}-0.{{ tpl .Values.replserver.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_hostname2: "{{ tpl .Values.replserver.podNameDc2 . }}-1.{{ tpl .Values.replserver.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_hostname3: "{{ tpl .Values.replserver.podNameDc2 . }}-2.{{ tpl .Values.replserver.serviceName . }}.{{ .Values.global.namespace }}.svc.{{ .Values.global.clusterDomain }}"
  hostAliases_ip1: ""
  hostAliases_ip2: ""
  hostAliases_ip3: ""
  podName: "{{ .Values.global.baseNameRS }}-us-{{ .Values.global.clusterId }}"
  podNameDc2: "{{ .Values.global.baseNameRS }}-us-{{ .Values.global.clusterId2 }}"
  secretName: "{{ .Values.global.baseNameRS }}-{{ .Values.global.clusterId }}"
  serviceName: "{{ .Values.global.serviceNameRS }}"