# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================

# Values file to aid configuring the deployment for local development
# To use, make sure you reference this file after the main global values file when calling `helm template`
# E.g. helm template -f values.yaml -f apps/values-local-dev-overrides.yaml access-manager apps/charts/access-manager > access-manager.yaml

global:
  registryURL: "local"
  imageTag: "latest"
  imgPullPolicy: "IfNotPresent"
  am:
    cpu: "1000m"
    memory: "2Gi"
  fact:
    cpu: "500m"
    memory : "512Mi"
  us:
    cpu: "500m"
    memory: "2Gi"
  ts:
    cpu: "500m"
    memory: "1Gi"
  aps:
    cpu : "500m"
    memory: "1Gi"
  rs:
    cpu: "500m"
    memory: "1Gi"
  ig:
    cpu: "500m"
    memory: "512Mi"
  idm:
    cpu: "500m"
    memory: "1Gi"