# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.aps.secretName . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    deploymentTime: {{ now | date "20060102T150405" | quote }}
type: Opaque
stringData:
  SECRET_PASSWORD_KEYSTORE_KEY: "{{ tpl .Values.aps.secret_password_keystore_key . }}"
  SECRET_PASSWORD_KEYSTORE: "{{ tpl .Values.aps.secret_password_keystore . }}"
  SECRET_PASSWORD_TRUSTSTORE: "{{ tpl .Values.aps.secret_password_truststore . }}"
  SECRET_PASSWORD_USER_ADMIN: "{{ tpl .Values.aps.secret_password_user_admin . }}"
  SECRET_PASSWORD_USER_AM: "{{ tpl .Values.aps.secret_password_user_am . }}"
  {{- if hasPrefix "prod" (lower .Values.global.envType) }}
  SECRET_CERTIFICATE: "{{ .Values.aps.secret_certificate | b64enc }}"
  SECRET_CERTIFICATE_KEY: "{{ .Values.aps.secret_certificatekey | b64enc }}"
  {{- else }}
    {{- $certdetails := dict "serviceName" (tpl .Values.aps.serviceName .) "release" $.Release -}}
    {{ ( include "midships.gen-certs" $certdetails ) }}
  {{- end }}