# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ tpl .Values.am.serviceName . }}-lb"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "{{ tpl .Values.am.podName . }}"
    deploymentTime: {{ now | date "20060102T150405" | quote }}
spec:
  type: LoadBalancer
  selector:
    app: "{{ tpl .Values.am.podName . }}"
  ports:
  - name: http1
    port: 80
    targetPort: {{ .Values.am.portHttp }}
    protocol: TCP
  - name: http2
    port: {{ .Values.am.portHttp }}
    targetPort: {{ .Values.am.portHttp }}
    protocol: TCP
  - name: http3
    port: {{ .Values.fact.portHttp }}
    targetPort: {{ .Values.fact.portHttp }}
    protocol: TCP
  - name: https1
    port: 443
    targetPort: {{ .Values.am.portHttps }}
    protocol: TCP
  - name: https2
    port: {{ .Values.am.portHttps }}
    targetPort: {{ .Values.am.portHttps }}
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.am.serviceName . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "{{ tpl .Values.am.podName . }}"
    deploymentTime: {{ now | date "20060102T150405" | quote }}
spec:
  clusterIP: None
  selector:
    app: "{{ tpl .Values.am.podName . }}"
  ports:
  - name: http1
    port: 80
    targetPort: {{ .Values.am.portHttp }}
    protocol: TCP
  - name: http2
    port: {{ .Values.am.portHttp }}
    targetPort: {{ .Values.am.portHttp }}
    protocol: TCP
  - name: http3
    port:  {{ .Values.fact.portHttp }}
    targetPort: {{ .Values.fact.portHttp }}
  - name: https1
    port: 443
    targetPort: {{ .Values.am.portHttps }}
    protocol: TCP
  - name: https2
    port: {{ .Values.am.portHttps }}
    targetPort: {{ .Values.am.portHttps }}
    protocol: TCP
