# ========================================================================
# MIDSHIPS
# COPYRIGHT 2023

# Legal Notice:
# Installation and use of this script is subject to a license agreement
# with Midships Limited (a company registered in England, under company
# registration number: 11324587). This script cannot be modified or
# shared with another organisation unless approved in writing by Midships
# Limited. You as a user of this script must review, accept and comply
# with the license terms of each downloaded/installed package that is
# referenced by this script. By proceeding with the installation, you are
# accepting the license terms of each package, and acknowledging that your
# use of each package will be subject to its respective license terms.
# For more information visit www.midships.io

# NOTE:
# Don't check this file into source control with any sensitive hard
# coded values.
# ========================================================================
idm:
  configmapName: "{{ .Values.global.baseNameIDM }}-{{ .Values.global.clusterId }}"
  dsRepo:
    port:
      httpPrimary: "8080"
      httpSecondary: "8080"
      httpsPrimary: "8443"
      httpsSecondary: "8443"
      ldapPrimary: "1389"
      ldapSecondary: "1389"
      ldapsPrimary: "1636"
      ldapsSecondary: "1636"
    security: "ssl"
  lbFQDN: "idmdc1.midships.io"
  podName: "{{ .Values.global.baseNameIDM }}-{{ .Values.global.clusterId }}"
  portHttp: "8080"
  portHttps: "8443"
  portMauth: "8444"
  profile: "ds"
  serviceName: "{{ .Values.global.serviceNameIDM }}"
  unamePrometheus: "prometheus"
userstore:
  podName: "{{ .Values.global.baseNameUS }}-{{ .Values.global.clusterId }}"
  serviceName: "{{ .Values.global.serviceNameUS }}"